#+title: My Doom Emacs config

* Table of Contents :toc:
- [[#doom-settings][Doom Settings]]
  - [[#font][Font]]
  - [[#theme][Theme]]
  - [[#lsp-settings][LSP Settings]]
- [[#emacs-settings][Emacs Settings]]
  - [[#misc][Misc]]
  - [[#fish-shell-workaround][Fish shell workaround]]
- [[#keybinds][Keybinds]]
- [[#org][Org]]
- [[#markdown][Markdown]]
- [[#elfeed][Elfeed]]

* Doom Settings
** Font
+ *doom-font*: the primary font to use.
+ *doom-variable-pitch-font*: a /non/-*monospace* font (where applicable).
+ *doom-big-font*: used for *doom-big-font-mode*, use this for presentations or streaming.
+ *doom-symbol-font*: for symbols.
+ *doom-serif-font*: for the *fixed-pitch-serif* face.
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMonoNL Nerd Font" :size 16)
      doom-variable-pitch-font (font-spec :family "Inter" :size 16))
#+end_src
** Theme
#+begin_src emacs-lisp
(setq doom-theme 'doom-tomorrow-night)
#+end_src
+ Disable function call italic style.
#+begin_src emacs-lisp
(custom-set-faces!
  '(font-lock-function-call-face :slant normal))
#+end_src
** LSP Settings
*** Go
+ Use *goimports* instead of *gofmt*.
#+begin_src emacs-lisp
(after! apheleia
  (setf (alist-get 'go-mode apheleia-mode-alist) 'goimports)
  (setf (alist-get 'go-ts-mode apheleia-mode-alist) 'goimports))
#+end_src
+ Add *tmpl* to web-mode.
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.tmpl\\'" . web-mode))
#+end_src
+ Set /tab size/ to *4*.
#+begin_src emacs-lisp
(after! go-ts-mode
  (setq go-ts-mode-indent-offset 4))
#+end_src

* Emacs Settings
** Misc
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
(setq confirm-kill-emacs nil)
(setq scroll-margin 8)
#+end_src
** Fish shell workaround
+ /Non/-*POSIX* compliant shells (particularly *Fish* and *Nushell*) can cause unpredictable issues with any Emacs utilities that spawn child processes from shell commands (like /diff-hl/ *TRAMP*, and *terminal emulators*).
#+begin_src emacs-lisp
(setq shell-file-name (executable-find "bash"))
(setq-default ghostel-shell "/bin/fish")
(setq-default explicit-shell-file-name "/bin/fish")
#+end_src

* Keybinds
#+begin_src emacs-lisp
(setq evil-escape-key-sequence "jk")

(map! :n "H" #'previous-buffer
      :n "L" #'next-buffer
      :i "C-S-v" #'clipboard-yank)
#+end_src

* Org
#+begin_src emacs-lisp
(custom-theme-set-faces!
  'doom-tomorrow-night
  '(org-level-8 :inherit outline-3 :height 1.0)
  '(org-level-7 :inherit outline-3 :height 1.0)
  '(org-level-6 :inherit outline-3 :height 1.1)
  '(org-level-5 :inherit outline-3 :height 1.2)
  '(org-level-4 :inherit outline-3 :height 1.3)
  '(org-level-3 :inherit outline-3 :height 1.4)
  '(org-level-2 :inherit outline-2 :height 1.5)
  '(org-level-1 :inherit outline-1 :height 1.6)
  '(org-document-title :height 1.8 :bold t :underline nil))

(setq org-directory "~/Org/")
(add-hook 'org-mode-hook #'hl-todo-mode)
#+end_src

* Markdown
#+begin_src emacs-lisp
(custom-set-faces
 '(markdown-header-face ((t (:inherit font-lock-function-name-face :weight bold :family "variable-pitch"))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.6))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.5))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :height 1.4))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face :height 1.3))))
 '(markdown-header-face-5 ((t (:inherit markdown-header-face :height 1.2))))
 '(markdown-header-face-6 ((t (:inherit markdown-header-face :height 1.1)))))

(defun dt/toggle-markdown-view-mode ()
  "Toggle between `markdown-mode' and `markdown-view-mode'."
  (interactive)
  (if (eq major-mode 'markdown-view-mode)
      (markdown-mode)
    (markdown-view-mode)))
#+end_src

* Elfeed
#+begin_src emacs-lisp
(add-hook! 'elfeed-search-mode-hook #'elfeed-update)
#+end_src
