# BEGIN_KITTY_THEME
# Doom One
include current-theme.conf
# END_KITTY_THEME
input_delay 0
repaint_delay 0
sync_to_monitor no

window_padding_width 1

font_size 12
font_family MesloLGS Nerd Font

enable_audio_bell no
confirm_os_window_close 0

cursor_blink_interval 0
scrollback_lines 10000

map kitty_mod+t launch --cwd=current --type=tab

scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'call nvim_open_term(0, {})' +'set nomodified nolist' +'$' -
