# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME

shell /usr/bin/fish

font_family Maple Mono NF
font_size 12

window_margin_width 3
enable_audio_bell no

scrollback_lines 10000

map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+q close_os_window
