# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x1f1f28ff
rootcolor = 0x1f1f28ff
bordercolor = 0x676785ff
dropcolor = 0x76946a80
splitcolor = 0x7e9cd8ff
focuscolor = 0x76946aff
maximizescreencolor = 0xc0a36eff
urgentcolor = 0xc34043ff
scratchpadcolor = 0x7e9cd8ff
globalcolor = 0x21321aff
overlaycolor = 0x5f481cff
jump_label_decorate_fg_color = 0xc8c093ff
jump_label_decorate_bg_color = 0x333343ff
jump_label_decorate_focus_fg_color = 0x1f1f28ff
jump_label_decorate_focus_bg_color = 0x76946aff
jump_label_decorate_border_color = 0x676785ff
group_bar_decorate_fg_color = 0xc8c093ff
group_bar_decorate_bg_color = 0x333343ff
group_bar_decorate_focus_fg_color = 0x1f1f28ff
group_bar_decorate_focus_bg_color = 0x76946aff
group_bar_decorate_border_color = 0x676785ff
