# Noctalia Theme for Mango
# Generated automatically by Noctalia

shadowscolor = 0x181926ff
rootcolor = 0x24273aff
bordercolor = 0x696f91ff
dropcolor = 0xb7bdf880
splitcolor = 0xc6a0f6ff
focuscolor = 0xb7bdf8ff
maximizescreencolor = 0x8aadf4ff
urgentcolor = 0xed8796ff
scratchpadcolor = 0xc6a0f6ff
globalcolor = 0x031af9ff
overlaycolor = 0x0244c9ff
jump_label_decorate_fg_color = 0xcad3f5ff
jump_label_decorate_bg_color = 0x3e435bff
jump_label_decorate_focus_fg_color = 0x181926ff
jump_label_decorate_focus_bg_color = 0xb7bdf8ff
jump_label_decorate_border_color = 0x696f91ff
group_bar_decorate_fg_color = 0xcad3f5ff
group_bar_decorate_bg_color = 0x3e435bff
group_bar_decorate_focus_fg_color = 0x181926ff
group_bar_decorate_focus_bg_color = 0xb7bdf8ff
group_bar_decorate_border_color = 0x696f91ff
