[app]
overall = { bg = "#192330", fg = "#cdcecf" }

[mgr]
cwd = { fg = "#f4a261", style = "bold" }

find_keyword = { fg = "#cdcecf", bg = "#3c5372" }
marker_marked = { bg = "#413d61" }
count_copied = { bg = "#dbc074" }
count_cut = { bg = "#c94f6d" }
count_selected = { bg = "#81b29a" }
marker_copied = { bg = "#dbc074" }
marker_cut = { bg = "#c94f6d" }
marker_selected = { bg = "#81b29a" }

border_style = { fg = "#71839b" }

[indicator]

[tabs]
active = { fg = "#192330", bg = "#71839b" }
inactive = { fg = "#aeafb0", bg = "#212e3f" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { bg = "#719cd6", fg = "#131a24", gui = "bold" }
normal_alt  = { bg = "#334761", fg = "#cdcecf" }
select_main = { bg = "#9d79d6", fg = "#131a24", gui = "bold" }
select_alt  = { bg = "#413d61", fg = "#cdcecf" }
unset_main = { bg = "#9d79d6", fg = "#131a24", gui = "bold" }
unset_alt  = { bg = "#413d61", fg = "#cdcecf" }

[status]
# perm_sep   = { fg = "darkgray" }
# perm_type  = { fg = "#aeafb0" }
# perm_read  = { fg = "yellow" }
# perm_write = { fg = "red" }
# perm_exec  = { fg = "cyan" }
# progress_label  = { bold = true }
# progress_normal = { fg = "green", bg = "black" }
# progress_error  = { fg = "yellow", bg = "red" }


[filetype]
rules = [
  { mime = "image/*", fg = "#b8b8ba" }
]

