gui:
  theme:
    activeBorderColor:
      - "#719cd6"   # Nightfox Blue
      - bold
    inactiveBorderColor:
      - "#52585f"   # Muted Surface/Gray
    optionsTextColor:
      - "#719cd6"   # Nightfox Blue
    selectedLineBgColor:
      - "#29313a"   # Surface 1 (Lighter Background)
    selectedRangeBgColor:
      - "#29313a"
    cherryPickedCommitBgColor:
      - "#29313a"
    cherryPickedCommitFgColor:
      - "#81b29a"   # Nightfox Green
    unstagedChangesColor:
      - "#c94f6d"   # Nightfox Red
    defaultFgColor:
      - "#cdcecf"   # Main Text Foreground

    searchingActiveBorderColor:
      - "#e0af68"   # Nightfox Yellow

    authorColors:
      "*": "#9d79d6"   # Nightfox Magenta/Purple
