gui:
  theme:
    activeBorderColor:
      - '#a9b665'
      - bold
    inactiveBorderColor:
      - '#928374'
    optionsTextColor:
      - '#7daea3'
    selectedLineBgColor:
      - '#3c3836'
    selectedRangeBgColor:
      - '#3c3836'
    cherryPickedCommitBgColor:
      - '#45403d'
    cherryPickedCommitFgColor:
      - '#7daea3'
    unstagedChangesColor:
      - '#ea6962'
    defaultFgColor:
      - '#d4be98'
