gui:
  theme:
    activeBorderColor:
      - '#a7c080' # Green
      - bold
    inactiveBorderColor:
      - '#3d484d' # Muted Grey
    optionsTextColor:
      - '#7fbbb3' # Blue
    selectedLineBgColor:
      - '#323c41' # Hard Selection Grey
    selectedRangeBgColor:
      - '#323c41'
    cherryPickedCommitBgColor:
      - '#4b565c'
    cherryPickedCommitFgColor:
      - '#d699b6' # Purple
    unstagedChangesColor:
      - '#e67e80' # Red
    defaultFgColor:
      - '#d3c6aa' # Main Text
    searchingActiveBorderColor:
      - '#dbbc7f' # Yellow
