# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

palette = "everforest"

[palettes.everforest]
rosewater = "#f3a0a0"
flamingo  = "#e67e80"
pink      = "#e67e80"
mauve     = "#d699b6"
red       = "#e67e80"
maroon    = "#e67e80"
peach     = "#e69875"
yellow    = "#dbbc7f"
green     = "#a7c080"
teal      = "#83c092"
sky       = "#7fbbb3"
sapphire  = "#7fbbb3"
blue      = "#7fbbb3"
lavender  = "#d699b6"
text      = "#d3c6aa"
subtext1  = "#9da9a0"
subtext0  = "#859289"
overlay2  = "#9da9a0"
overlay1  = "#859289"
overlay0  = "#4f585e"
surface2  = "#475258"
surface1  = "#3d484d"
surface0  = "#343f44"
base      = "#2d353b"
mantle    = "#232a2e"
crust     = "#1e2326"

[character]
success_symbol = '[󰘧](bold green)'
error_symbol = '[󰘧](bold red)'
vimcmd_symbol = '[󰘧](bold green)'
vimcmd_replace_one_symbol = '[](bold yellow)'
vimcmd_replace_symbol = '[](bold yellow)'
vimcmd_visual_symbol = '[](bold orange)'

[username]
show_always = true
format = '[$user]($style)[@](orange)'
style_user = "blue"
style_root = "red bold"

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
truncation_length = 4
style = "bold green"
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[git_branch]
style = "bold purple"
symbol = " "

[git_status]
style = "yellow"

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_only = false
ssh_symbol = " "
style = "cyan"

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
