[scrolling]
history = 10000
multiplier = 3

[window]
padding = { x = 4, y = 4 }

[font]
normal = { family = "Maple Mono Normal NL NF", style = "Regular" }
bold = { family = "Maple Mono Normal NL NF", style = "Bold" }
italic = { family = "Maple Mono Normal NL NF", style = "Italic" }
bold_italic = { family = "Maple Mono Normal NL NF", style = "Bold Italic" }
size = 12.0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#282c34'
foreground = '#bbc2cf'

[colors.normal]
black   = '#282c34'
red     = '#ff6c6b'
green   = '#98be65'
yellow  = '#ecbe7b'
blue    = '#51afef'
magenta = '#c678dd'
cyan    = '#46d9ff'
white   = '#bbc2cf'

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Middle", mods = "None", action = "PasteSelection" },
]
