[window]
padding = { x = 5, y = 5 }
startup_mode = "Maximized"

[font]
size = 12

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Q"
mods = "Control|Shift"
action = "Quit"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
live_config_reload = true
working_directory = "None"
